name: React app deployment

on:
  push:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react application to github pages with gh-pages
      uses: ShanuDey/deploy-react-to-ghpages@v1.0
